#!/bin/bash

[ $(id -u) == 0 ] || SUDO=sudo
$SUDO apt-get update
$SUDO apt-get install -y git python-virtualenv gcc g++ python-all-dev libpython3-all-dev cmake

git submodule sync
git submodule update --force --init --recursive

rm -fr virtualenv .tox
virtualenv virtualenv
source virtualenv/bin/activate
pip install -v -e .
pip install tox
