.\" -*- nroff -*-
.\" Copyright (C) 2017 Loic Dachary
.\" This file is part of python-crush
.\" Author: Loic Dachary <loic@dachary.org>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License version 3 as
.\" published by the Free Software Foundation.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software Foundation,
.\" Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.TH crush 8 "April 2017" "python-crush"
.SH NAME
crush - tool for modelling/analyzing CRUSH maps
.SH SYNOPSIS
.B crush --help
.LP
.SH DESCRIPTION
.B crush
The crush module wraps the libcrush C library implementing CRUSH, a scalable
pseudo-random data distribution function designed for distributed object
storage systems that efficiently maps data objects to storage devices without
relying on a central directory.
.LP
.SH AUTHOR
.B crush
is part of the
.B python-crush
package, which was written by Loic Dachary <loic@dachary.org>.
